# Imports

In [ ]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report

In [61]:
path = os.path.join('data', 'filtered-enem-2019.csv')
df = pd.read_csv(path)
df.head()

,NU_ANO,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_ESCOLA,NU_NOTA_REDACAO,TP_ST_CONCLUSAO
0,2019,397.7,380.8,532.8,480.5,1,580,1
1,2019,402.8,448.9,489.6,521.1,2,580,2
2,2019,445.3,446.5,526.0,519.3,2,900,2
3,2019,385.6,428.0,429.5,447.2,1,520,1
4,2019,627.0,637.0,583.9,725.0,1,860,1

In [62]:
def classificar_redacao(nota):
    if nota <= 400:
        return "baixa"
    elif nota <= 800:
        return "media"
    else: 
        return "alta"

df['REDACAO_CLASSIF'] = df['NU_NOTA_REDACAO'].apply(classificar_redacao)

A nota da redação foi transformada em uma váriavel categórica `REDACAO_CLASSIF` com três classes: baixa, média e alta. O objetivo é facilitar a identificação de padrões de desempenho dos candidatos.

In [63]:
features = ['NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT',
       'TP_ESCOLA','TP_ST_CONCLUSAO']

X = df[features]
y = df['REDACAO_CLASSIF']

X = pd.get_dummies(X,columns=["TP_ESCOLA", "TP_ST_CONCLUSAO"],drop_first=True)
X.head()

,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_ESCOLA_2,TP_ESCOLA_3,TP_ST_CONCLUSAO_2,TP_ST_CONCLUSAO_3,TP_ST_CONCLUSAO_4
0,397.7,380.8,532.8,480.5,False,False,False,False,False
1,402.8,448.9,489.6,521.1,True,False,True,False,False
2,445.3,446.5,526.0,519.3,True,False,True,False,False
3,385.6,428.0,429.5,447.2,False,False,False,False,False
4,627.0,637.0,583.9,725.0,False,False,False,False,False

As variaveis explicativas(features) são as áreas de conhecimento junto com as caracteristicas educacionais do candidato. A variavel alvo corresponde a classificação de desempenho da redação.

As variáveis categóricas também foram transformadas em one-hot encoding. A opção drop_first=True foi utilizada para evitar problemas de multicolinearidade, mantendo uma categoria como referência.

In [64]:
X_train, X_test, y_train, y_test = train_test_split( X, y,test_size=0.2,random_state=42, stratify= y)

rf = RandomForestClassifier(n_estimators=200, max_depth= 10, random_state= 42)

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=200, random_state=42)

O conjunto de dados foi dividido em 80% para treino e 20% para teste. Foi utilizado o stratify para manter as proporções das classes. 

O Random Forest Classifier foi escolhido por ser mais eficiente em processar multiplas variáveis e capturar padrões mais complexos.

In [71]:
y_pred = rf.predict(X_test)

In [66]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.774

O modelo apresentou 77% de acurácia.

In [67]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

        alta       0.70      0.27      0.39       205
       baixa       0.38      0.02      0.03       276
       media       0.78      0.98      0.87      1519

    accuracy                           0.77      2000
   macro avg       0.62      0.42      0.43      2000
weighted avg       0.72      0.77      0.70      2000

A analise mais detalhada mostrou que há um recall de 98% para classe média enquanto as classes baixa e alta apresentam valores significativamente inferiores ( 2% e 27%),isso mostra que o modelo é incapaz de identificar adequadamente os extremos de desempenho.

In [70]:
rf_balanced = RandomForestClassifier(n_estimators=300, max_depth= 12,class_weight='balanced', random_state= 42)

rf_balanced.fit(X_train, y_train)

y_pred_balanced = rf_balanced.predict(X_test)
accuracy_balanced = accuracy_score(y_test, y_pred_balanced)
accuracy_balanced

0.6645

Para melhorar a identificação as classes minoritárias, nesse segundo modelo foi utilizado um novo parametro: `class_weight= 'balanced'`, que penaliza mais os erros cometidos nas classes menos frequentes.

Foi observado uma redução da acurácia global (66%) porém houve uma melhora significativa no recall das classes baixa e alta, mostrando que o modelo tem uma maior capacidade de identificar os extremos de desempenho.

In [69]:
print(classification_report(y_test,y_pred_balanced))

              precision    recall  f1-score   support

        alta       0.44      0.51      0.47       205
       baixa       0.33      0.60      0.43       276
       media       0.84      0.70      0.76      1519

    accuracy                           0.66      2000
   macro avg       0.54      0.60      0.55      2000
weighted avg       0.73      0.66      0.68      2000

Conclui-se que as variáveis utilizadas são relevantes, porém insuficientes para diferenciar com alta precisão os níveis extremos de desempenho.